spring:
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:file:./target/question
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update

springdoc:
    swagger-ui:
        path: /api-docs
        operationsSorter: method
